DECLARE @sql NVARCHAR(MAX);
DECLARE @local_vars NVARCHAR(MAX);

BEGIN TRANSACTION;
BEGIN TRY
	SET @sql = ?;
  SET @local_vars = ?;
  
EXEC sp_executesql @sql;

COMMIT TRANSACTION;
END TRY
BEGIN CATCH
	THROW
  ROLLBACK TRANSACTION;
END CATCH;